version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    links: 
      - mysql:db
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8081:80'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    #restart: always
    #restart: on-failure
    ports:
        - "3306:3306"
    volumes:
        - ./../mysql:/var/lib/mysql
    # задаем пароль для root пользователя
    environment:
        - MYSQL_DATABASE=mouse
        - MYSQL_USER=mouse1
        - MYSQL_PASSWORD=root1
        - MYSQL_ROOT_PASSWORD=root
        - TZ=UTC
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    #links: mysql #for mysql container - "db:db"     
    #sudo docker-compose.exe exec mysql -u pac -p root1 pac < pac.sql
    #sudo docker-compose exec mysql --host=127.0.0.1 --port=3306 -u pac -p root1 pac < /home/straengel/projects/pac.sql
